CREATE TABLE employees (
    employee_id         NUMBER(7,0) CONSTRAINT employee_id_pk PRIMARY KEY,
    first_name          VARCHAR2(40),
    last_name           VARCHAR2(40),
    phone_number        VARCHAR2(20),
    email               VARCHAR2(60),
    nid_number          VARCHAR2(30),
    date_of_birth       DATE,
    religion            VARCHAR2(50),
    gender              VARCHAR2(40),
    maritual_status     VARCHAR2(50),
    father_name         VARCHAR2(60),
    mother_name         VARCHAR2(60),
    emergency_contract  VARCHAR2(30),
    present_address     VARCHAR2(200),
    permanent_address   VARCHAR2(200),
    join_date           DATE,
    job_id              VARCHAR2(30),
    salary              NUMBER(12,2),
    emp_image           BLOB,
    department_id       NUMBER(7,0),
    remarks             VARCHAR2(200),
    emp_status          VARCHAR2(30)
);
